keys:
  - &admin_florian 8BAF9A2054C98791F510C72641120FB11592EAFF
  - &hyrule_city 46ff20f9390ae67c03a2fd465422c3d5974a7622
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - pgp:
        - *admin_florian
        - *hyrule_city
